// examples/react/hello-world/src/Spin.js
import React from 'react';
import './assets/js/spin.js';
import './assets/css/spin.css';
import './assets/css/custom-spin.css';

class Spin extends React.Component {
    render() {
        return 	(<tau-spin class="default-spin"
		min="1902"
		max="2050"
		value="2002"
		loop="enabled"
		roll-height="custom"
		item-height="50"
		momentum-level="1"
		duration="500">
	    </tau-spin>
    )}
}

export default Spin;

// examples/vue/todo-list/src/components/Spin.vue
<template>
	<tau-spin class="default-spin"
		min="1902"
		max="2050"
		:value=year
		loop="enabled"
		roll-height="custom"
		item-height="50"
		momentum-level="1"
		duration="500">
	</tau-spin>
</template>

<script>
import '../lib/spin.js';

export default {
	name: 'Spin',
	data: function() {
		return {
			year: 2020
		}
	}
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
@import '../lib/spin.css';

.default-spin {
	height: 150px;
	font-size: 50px;
	width: 200px;
}
.default-spin .ui-spin-item-selected {
	font-size: 50px;
}
</style>
